version: "2.1"

services:

  v4_0_5:
    container_name: CVE_2022_34265_v4.0.5
    build: ./
    ports:
      - 4131:8000
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: vuln
      POSTGRES_PASSWORD: vuln
      PGPASSWORD: vuln
      POSTGRES_DB: vuln
      TZ: "Asia/Tokyo"
      PGPORT: 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

